### ISSUE TITLE
chore: update hubs CTAs

### ISSUE THREAD

**Issue by ssspear** [stoplightio/stoplight.io#1115]
**Chore summary**
Update requested button text to read "Free trial. No cc required."

**Tasks**
- [x] Hero CTA: Change 'Get Started Now' button
- [x] ActionBar CTA: Change 'Get Started Now' button
- [x] PricingSection Buttons: Change Standard & Pro
