### ISSUE TITLE
Add Zoom video to Hubs page

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1259]
**Chore summary**
Add Tim Slagle's testimonial video to https://stoplight.io/hubs/

**Tasks**
- [ ] Decide where on the page is a possible place to embed the video
- [ ] Decide where on the page is a possible place and also an aesthetically pleasing place
- [ ] Embed the same video found on https://stoplight.io/case-studies/zoom-video/ 

**Additional context**
Add any other context about the chore here.

**wireframe**
[just an idea](https://www.canva.com/design/DADrlNZvJ9I/sRDT9TIilI1a8YaGhAm71A/view?website#4)

**iframe provided by youtube**
`<iframe width="560" height="315" src="https://www.youtube.com/embed/jLRDAYRKqTg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**code currently in use on the case study page**
`<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/jLRDAYRKqTg' frameborder='0' allowfullscreen></iframe></div>`

**Comment by ksatx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Zoom video to hubs pages](https://trello.com/c/1cztrjVJ/241-add-zoom-video-to-hubs-pages)

**Comment by ksatx** [comment]
![canva wireframe for hubs](https://user-images.githubusercontent.com/51092436/69184603-cc013180-0ada-11ea-89fe-23e396455be3.png)
