### ISSUE TITLE
chore/early access pricing

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1450]
**Chore summary**
Get an early access pricing page up, before launch and ahead of the other site updates contained in #1436

**Tasks**
- [x] Add Pricing Link to Header
- [x] Update H1 to "Plans That Fit Your API Program"
- [ ] Update plan names to Starter, Growth, Mature, Enterprise
- [ ] Insert persona between Plan name and price
- [ ] Update details within the plan tiles
- [x] Add Form Input Boxes to Plan Cards
- [x] Update CTA text on each plan to read "Request Early Access"
- [ ] Add CTAs under plan names on the feature grid, that scroll along
- [ ] Update and condense feature grid
- [x] Remove tooltips from feature grid (or if they get finished, keep the)
- [x] Expand FAQs/Remove accordion effect
- [ ] Ensure Styling for pricing page doesn't break other or adversely effect other pages

**Additional context**

Details on content changes spelled out in this google sheet [https://docs.google.com/spreadsheets/d/1Uqn-5mF5IgP15NaqXOYTuIcMX8TAzlwpYnC_5ILFo7U/edit#gid=1339523622](https://docs.google.com/spreadsheets/d/1Uqn-5mF5IgP15NaqXOYTuIcMX8TAzlwpYnC_5ILFo7U/edit#gid=1339523622)

We want the tooltips when the rest of the site updates go live, but if they slow down getting the early access pricing page up, it's okay to disable them

![EarlyAccessMockup](https://user-images.githubusercontent.com/51092436/81615202-d70c8e80-93a6-11ea-9cef-d496724174f5.png)
