### ISSUE TITLE
feedback: early access pricing page

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1454]
**Chore summary**
Items related to #1452 that Growth needs feedback from other stakeholders.

**Items for Feedback**
- [x] Blocking free email providers
- [x] Add to a list and vet, or automatically send out the sign-up link?
- [x] plan card bullet points need to be evened out, what should we add or subtract?
- [x] Plan names to Starter, Growth, Mature, Enterprise?
- [x] Per Marc, add a user cap on the Pro Plan (how many? we put in 50 as a starting point for discussion)
- [x] update FAQs to reflect that we don't charge for Guest Users (I removed the sentence about Guest Users, but that's not the same as saying that we don't charge for them. Need input on wording)
- [x] Logos under "Leading Organizations Trust Stoplight with their APIs" - are they current customers and are these logos approved to use?

**Tasks**
- [x] Add Pricing Link to Header
- [x] Update H1 to "Plans That Fit Your API Program"
- [x] Add Form Input Boxes to Plan Cards
- [x] Update CTA text on each plan to read "Request Early Access"
- [x] Expand FAQs/Remove accordion effect
- [x] move "Everything in xyz" line item to the top of the list
- [x] per Marc, remove No User Cap altogether - it's kind of confusing with the per-user pricing
- [x] Change free to up to 10 projects
- [x] Change starter to up to 50 projects
- [x] Move custom domains over to free card
- [x] "Up-to-date mocking" -> "Instant mock servers"
- [x] Remove shared style guides from pro, we don't have them yet
- [x] Add line for multiple git branches support to the start plan
- [x] Add whitelabeling to the pro plan
- [x] Add guest role to pro plan
- [x] Remove private documentation from pro plan (no longer a thing, since workspace is your docs)
- [x] Remove activity logs from pro plan (not in product yet)
- [x] On free card, Design Validation -> API Style Guides (spectral guides in your project, this is not shared style guides which we don't have yet)
- [x] updated FAQs to reflect that we offer free starter plans to organizations helping in the COVID 19 fight.
- [x] Remove "workspaces" from the free card, since does not mean anything on it's own
- [x] Per Marc, change prices to be their actual starting cost, e.g. $99 and $399
- [x] Per Marc, update $x / user to $x / additional user for a stronger implication that it comes with a user
- [x] Reduce padding at bottom of pricing cards so that it is equal to the left/right padding
- [x] Reduce the size of the plus icon next to per-user cost, try out fal (light style icon)
- [x] update feature breakdown accordingly based on the pricing card changes

**Additional 2nd Priority Tasks**
- [x] Insert persona between Plan name and price
- [ ] Add CTAs under plan names on the feature grid, that scroll along
- [ ] Update and condense feature grid

**Additional context**

Details on content changes spelled out in this google sheet [https://docs.google.com/spreadsheets/d/1Uqn-5mF5IgP15NaqXOYTuIcMX8TAzlwpYnC_5ILFo7U/edit#gid=1339523622](https://docs.google.com/spreadsheets/d/1Uqn-5mF5IgP15NaqXOYTuIcMX8TAzlwpYnC_5ILFo7U/edit#gid=1339523622)

**Comment by ksatx** [comment]
First-round feedback from @marbemac. I will add action items to the issue checklist.

> ### In the top cards
> ​
> 1. I suggest moving the "Everything in xyz" line item to the top of the list
> 2. I suggest removing `No User Cap` altogether - it's kind of confusing with the per user pricing.
> 3. I suggest updating the prices to be their actual starting cost, e.g. $99 and $399
> 4. Related to number 3, update `$x / user` to `$x / additional user` for a stronger implication that it comes with a user
> 5. Change free to up to 10 projects
> 6. Change starter to up to 50 projects
> 7. Reduce size of the plus icon next to per user cost, try out fal (light style icon)
> 8. Reduce padding at bottom of pricing cards so that it is equal to the left/right padding
> 9. Remove "workspaces" from the free card, since does not mean anything on it's own
> 10. Move custom domains over to free card
> 11. "Up-to-date mocking" -> "Instant mock servers"
> 12. Remove shared style guides from pro, we don't have them yet
> 13. Add line for multiple git branches support to the start plan
> 14. Add whitelabeling to the pro plan
> 15. Add guest role to pro plan
> 16. Remove private documentation from pro plan (no longer a thing, since workspace is your docs)
> 17. Remove activity logs from pro plan (not in product yet)
> 18. On free card, `Design Validation` -> `API Style Guides` (spectral guides in your project, this is not shared style guides which we don't have yet)
> ​
> ### Feature Breakdown
> ​
> Have not had time to look at this yet. But do update accordingly where makes sense based on the pricing card comments above.
> ​
> ### FAQs
> ​
> > This includes Guest users with access to a subset of projects. Anonymous users accessing your documentation are not counted as Stoplight users.
> ​
> I do not think that we should charge for guest users. Instead, I suggest we add a cap on the pro plan, and unlimited on enterprise plan. If we're cool with the pro plan cap, then can work that cap into the pro plan pricing card guest role line.
> ​
> > Do you offer discounts for Nonprofits or Open Source projects?
> ​
> I think that we should offer free plans to organizations helping in the covid 19 fight.
>

**Comment by ksatx** [comment]
Combined tasks from #1450 into this issue

**Comment by ksatx** [comment]
@paulatulis I tackled the low hanging fruit from Marc, the last 4 are styling so they're safer in your hands

**Comment by paulatulis** [comment]
@ksatx thank you so much for taking care of those items! I am looking at the rest now. By 'stray infinity signs' do you mean the one that is still on the professional card? I don't see more than that.
<img width="331" alt="Screen Shot 2020-05-18 at 8 58 37 AM" src="https://user-images.githubusercontent.com/47359669/82221553-c64ba380-98e5-11ea-9a03-c2c1e2ce5094.png">


Also, I am going to wait until we have the final bullet items on the pricing cards before I update the grid. Looks like there are still some lingering question marks that we need to resolve as a team as well as even out the lengths on each card. Does that sound accurate?

**Comment by ksatx** [comment]
Just adding in what we talked about on Zoom, "stray infinity signs" was a bug displaying on my local server, it's not showing up in the deploy preview so we're good.

Yes, the grid updates can wait until we get all the other feedback we need. The only item that for sure needs to be removed is "Private Documentation"

**Comment by ksatx** [comment]
Resolve by #1452
