### ISSUE TITLE
chore: clean up legacy product references

### ISSUE THREAD

**Issue by texas-kristen** [stoplightio/stoplight.io#1455]
**Chore summary**

Generally, remove, edit, or add a disclaimer to Next & Classic references throughout the site.

**Feedback**

From Collin -
>  re: version confusion, it would be nice to eventually see via google traffic coming into deprecated endpoints, and automatically redirect them to the latest version. Ex. https://apitesting.jamesmessinger.com/stoplight/ links to http://stoplight.io/platform/scenarios/
> Old blog posts, ex. https://www.google.com/search?q=stoplight+visualize+api
> All the traffic coming into api-docs.io, etc.
> I always harp on this stuff because it's such a big deal to me in the products I use.
> Like CircleCI vs. Github vs. AWS are worlds apart in terms of API stability, whether I trust them not to break or deprecate a feature in 6 months, how easy it is to find the docs version, etc.
> As a developer I generally try to avoid integrating tightly with a product that feels like it's going to change on me or like it might be a beta version
> Here's a good example of communicating different versions done right:
> First google result for "github api":
> https://developer.github.com/v3/#current-version
> Right at the top of the API v2 docs, there are links to the newer v4 API, and links to this summary page, explaining the currently available versions of the API: https://developer.github.com/v3/versions/
> I can see there that the v2 API was deprecated in 2012, and I can infer that the v3 API will have at least a few years of support.
> This all inspires confidence that I can depend on Github and its API in my workflows

**Tasks**

**On 'Introducing Scenarios'**
- [x] Add a disclaimer to the top and bottom of the blog that this is a legacy product that is no longer available/supported
- [x] remove link to classic
- [x] edit references to v2 such as "We are developing v2 and v3 in tandem, and will be including next generation versions of v2 systems like mocking, modeling, and docs, in v3 over the next few months."

**On Getting Started with API Design**
- [ ] Get input from Phil on how to best update [Getting Started with API Design using Stoplight and OpenAPI](https://stoplight.io/blog/getting-started-with-api-design-using-stoplight-and-openapi-90fc8f37ac2e/) or add disclaimers

**On [Hosted API Documentation](https://stoplight.io/documentation/hosted/)**
- [ ] Get specifics on what needs to change

**On Home**
- [x] Update meta image, currently using /images/home-hero.png

- [ ] /blog/api-documentation-build-buy
- [ ] /api-design-guide/tooling
- [ ] /mock-json-generator/
- [ ] /blog/the-stoplight-way-versions-and-releases-ba7009e51bab
