### ISSUE TITLE
chore/ add newsletter subscription form to the site

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1460]
**Tasks**
- [x] evaluate past newsletter subscription form, see if it's still applicable
- [x] create one-line form to use in action bar/narrower CTA areas
- [x] determine the best place to put, somewhere easy to direct people to

**Comment by ksatx** [comment]
fixed in #1462
