### ISSUE TITLE
chore/ homepage template redesign

### ISSUE THREAD

**Issue by ksatx** [stoplightio/stoplight.io#1464]
**Tasks to Include on #1436 **
- [ ] Remove gif from homepage hero
- [x] Move Case Studies, Design Guide, Mocking Guide, and Documentation Guide into a different Header item (maybe Resources? It would be good to put https://stoplight.io/about/ in there as well, we can workshop the actual link name)
- [ ] Add the rest of the content from [https://docs.google.com/document/d/1b_Co0_gcn8kGNevd0xX_N-0Db_kCTMdPVmpx0cN7FZM/edit?usp=sharing](https://docs.google.com/document/d/1b_Co0_gcn8kGNevd0xX_N-0Db_kCTMdPVmpx0cN7FZM/edit?usp=sharing)
- [x] Style 'Solutions' items to be larger
- [ ] Move action bar up the page
- [x] Add 'favorite VCS' section
- [x] "Get Started" and "Start" should be condensed into one button
